services:
  postgres:
    container_name: postgres-sql-bn
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POTGRES_DB: blognote
    volumes:
      - type: volume
        source: postgres
        target: /var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - spring-bn
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-bn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

volumes:
  postgres:
    driver: local

networks:
  spring-bn:
    driver: bridge